name: ci

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ci disabled"

      # - uses: actions/checkout@v4
      #
      # - uses: oven-sh/setup-bun@v2
      #   with:
      #     bun-version: latest
      #
      # - run: bun install --frozen-lockfile
      #
      # - run: bun run lint
      #
      # - run: bun run typecheck
      #
      # - run: bun run build
